# Generated by Django 3.1.6 on 2021-02-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grower',
            fields=[
                ('grower_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('zip', models.IntegerField(null=True)),
                ('user', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
