# Generated by Django 3.1.6 on 2021-04-24 14:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryList',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CropList',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grower',
            fields=[
                ('grower_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('zip_code', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('trial_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('crop', models.CharField(max_length=50, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now, null=True)),
                ('notes', models.CharField(max_length=50, null=True)),
                ('country', models.CharField(max_length=50, null=True)),
                ('user', models.CharField(max_length=50, null=True)),
                ('grower_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trials.grower')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=50, null=True)),
                ('timing', models.CharField(max_length=50, null=True)),
                ('rate', models.CharField(max_length=50, null=True)),
                ('unit', models.CharField(max_length=50, null=True)),
                ('treatment', models.IntegerField(null=True)),
                ('trial_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trials.trial')),
            ],
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('measure_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('measure', models.CharField(max_length=50, null=True)),
                ('unit', models.CharField(max_length=50, null=True)),
                ('timing', models.CharField(max_length=50, null=True)),
                ('value', models.CharField(max_length=50, null=True)),
                ('treatment', models.IntegerField(null=True)),
                ('trial_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trials.trial')),
            ],
        ),
    ]
