# Generated by Django 3.1.6 on 2021-02-13 17:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('trial_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('crop', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('notes', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.CharField(max_length=100, null=True)),
                ('grower_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trials.grower')),
            ],
        ),
    ]
