# Generated by Django 3.1.6 on 2021-02-17 01:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('trial_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('crop', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('notes', models.CharField(max_length=50, null=True)),
                ('user', models.CharField(max_length=50, null=True)),
                ('grower_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trials.grower')),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('treatment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Treatment', models.CharField(max_length=50, null=True)),
                ('unit', models.CharField(max_length=50, null=True)),
                ('timing', models.CharField(max_length=50, null=True)),
                ('value', models.FloatField(null=True)),
                ('type_of_treatment', models.CharField(max_length=50, null=True)),
                ('trial_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trials.trial')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=50, null=True)),
                ('timing', models.CharField(max_length=50, null=True)),
                ('rate', models.FloatField(null=True)),
                ('rate_unit', models.CharField(max_length=50, null=True)),
                ('treatment_id', models.CharField(max_length=50, null=True)),
                ('trial_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trials.trial')),
            ],
        ),
    ]
