# Generated by Django 3.1.6 on 2021-02-13 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('measure_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('measure', models.CharField(blank=True, max_length=150, null=True)),
                ('unit', models.CharField(blank=True, max_length=150, null=True)),
                ('timing', models.CharField(blank=True, max_length=150, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('treatment_id', models.CharField(blank=True, max_length=50, null=True)),
                ('trial_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trials.trial')),
            ],
        ),
    ]
