# Generated by Django 3.1.6 on 2021-02-17 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0003_auto_20210217_0133'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Groer',
            new_name='Grower',
        ),
        migrations.AddField(
            model_name='trial',
            name='grower_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trials.grower'),
        ),
    ]
