# Generated by Django 3.1.6 on 2021-02-17 19:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0004_measure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grower',
            old_name='zip',
            new_name='zip_code',
        ),
        migrations.RemoveField(
            model_name='grower',
            name='user',
        ),
        migrations.RemoveField(
            model_name='measure',
            name='treatment_id',
        ),
        migrations.AddField(
            model_name='measure',
            name='type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='grower',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='measure',
            name='measure',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='measure',
            name='timing',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='measure',
            name='unit',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='measure',
            name='value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='rate_unit',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='timing',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='treatment_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trial',
            name='crop',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trial',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='trial',
            name='notes',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trial',
            name='user',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
