# Generated by Django 3.1.6 on 2021-02-17 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0004_measure'),
        ('trials', '0004_auto_20210217_0134'),
    ]

    operations = [
    ]
