# Generated by Django 3.1.6 on 2021-02-17 02:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0005_merge_20210217_0209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measure',
            name='treatment_id',
        ),
        migrations.AddField(
            model_name='measure',
            name='type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='measure',
            name='measure',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='measure',
            name='timing',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='measure',
            name='unit',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='measure',
            name='value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='trial',
            name='crop',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trial',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.DeleteModel(
            name='Treatment',
        ),
    ]
