# Generated by Django 3.1.6 on 2021-03-02 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0006_treatment'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table=('product', 'timing', 'rate', 'rate_unit', 'treatment_id'),
        ),
    ]
