# Generated by Django 3.1.6 on 2021-04-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0006_treatment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryList',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CropList',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='rate_unit',
            new_name='unit',
        ),
        migrations.RemoveField(
            model_name='measure',
            name='type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='treatment_id',
        ),
        migrations.AddField(
            model_name='measure',
            name='treatment',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='treatment',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='trial',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='measure',
            name='value',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='rate',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Treatment',
        ),
    ]
