# Generated by Django 3.1.6 on 2021-03-09 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0007_auto_20210309_1645'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Treatment',
        ),
    ]
