# Generated by Django 3.1.6 on 2021-02-17 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0007_auto_20210217_0223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('measure_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('measure', models.CharField(max_length=50, null=True)),
                ('unit', models.CharField(max_length=50, null=True)),
                ('timing', models.CharField(max_length=50, null=True)),
                ('value', models.FloatField(null=True)),
                ('type', models.CharField(max_length=50, null=True)),
                ('trial_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trials.trial')),
            ],
        ),
    ]
