# Generated by Django 3.1.6 on 2021-03-02 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0007_auto_20210302_1035'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
