# Generated by Django 3.1.6 on 2021-02-17 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0008_measure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grower',
            name='user',
        ),
    ]
