# Generated by Django 3.1.6 on 2021-03-02 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0008_auto_20210302_1043'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table=None,
        ),
    ]
