# Generated by Django 3.1.6 on 2021-03-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0008_delete_treatment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measure',
            name='type',
        ),
        migrations.AddField(
            model_name='measure',
            name='treatment',
            field=models.IntegerField(null=True),
        ),
    ]
