# Generated by Django 3.1.6 on 2021-03-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0009_auto_20210327_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='value',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
