# Generated by Django 3.1.6 on 2021-04-05 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0010_countrieslist_productlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CountriesList',
            new_name='CountryList',
        ),
    ]
