# Generated by Django 3.1.6 on 2021-03-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0010_auto_20210303_0929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treatment',
            old_name='treatment_name',
            new_name='timing',
        ),
        migrations.AddField(
            model_name='treatment',
            name='unit',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
