# Generated by Django 3.1.6 on 2021-03-03 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0011_auto_20210303_0937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treatment',
            old_name='timing',
            new_name='treatment_name',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='unit',
        ),
    ]
