# Generated by Django 3.1.6 on 2021-04-07 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0011_auto_20210405_1212'),
        ('trials', '0010_auto_20210330_1735'),
    ]

    operations = [
    ]
