# Generated by Django 3.1.6 on 2021-03-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0012_auto_20210303_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rate_unit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='timing',
        ),
        migrations.RemoveField(
            model_name='product',
            name='treatment_id',
        ),
        migrations.AddField(
            model_name='product',
            name='hybrid',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='treatment',
            field=models.IntegerField(null=True),
        ),
    ]
