# Generated by Django 3.1.6 on 2021-04-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0013_croplist'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
