# Generated by Django 3.1.6 on 2021-03-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0014_auto_20210309_0841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='rate_unit',
            new_name='unit',
        ),
        migrations.AlterField(
            model_name='product',
            name='rate',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
